---
title: "Untitled"
author: "George Kachergis"
date: "4/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Introduction

The quantity and quality of early language input has been found to be strongly associated with later language and academic outcomes [@Hart1995; @Marchman2008; @Cartmill2013; @HirshPasek2015; see @Schwab2016 for a review]. Thus, because of the potential for large downstream effects [@Heckman2006], there is tremendous interest in interventions that change children's language environment. 
And because parents define a large portion of that environment, especially before the onset of formal schooling, parent behavior is a critical locus for such interventions. 
Many effective parenting interventions require large resource investments and require many hours of in-person contact [@Jamaica2014; @PerryPreschool2004; @Leung2018], making implementation at scale a daunting proposition. 
For this reason, many researchers targeting early language are interested in delivering parenting interventions remotely -- through texts, apps, and videos delivered on digital devices. 
But what do parents take away from these short messages about what to do with or how to talk with their children?

The content provided by digital parenting interventions runs the gamut from general parenting messages and facts from child development research to specific advice and suggested activities. 
A growing body of evidence suggests that these digital interventions can be effective across a range of cultures, income levels, and children's ages [for a review, see @Breitenstein2014].
For example, in contrast to a face-to-face parent training intervention, a tablet-based version saw significantly higher session completion rates (51% attendance vs. 85% module completion) and comparable or larger effect sizes on parents' and children's (aged 2 to 5 years) behavior [@Breitenstein2016].
Often, however, the theory of change presupposed by such interventions is relatively vague.
Both within and outside the realm of academic interventions, messages to parents of young children often seek to provide knowledge about some aspect of development (e.g., early language), often in tandem with a suggestion regarding activities.
Such messages are assumed to inform parents' choice of behaviors, spurring them to engage in some target activity, which is assumed to be more stimulating than what parents would have done otherwise. 

This theory of change is typically grounded in ideas about guided play and early language stimulation. 
Child-directed speech varies not only in quantity (i.e., the number of total tokens), but also in quality in terms of the diversity of the tokens [@Malvern2004] or the context-appropriateness of the speech [@Cartmill2013], both of which have been linked to children's subsequent language development.
Further, language learning---especially the acquisition of early vocabulary in the first years---appears to be supported preferentially by parents and children _jointly attending_ to some object or activity [@Baldwin1991; @Bigelow2004].
Episodes of joint attention are frequent during guided play, when parents set goals and scaffold their child's activities [@Wood1976; @Weisberg2013].
Thus, the current literature supports interventions that encourage parents to provide high-quality language and interaction through something like guided play---whether via reading books or playing with a shape-sorter at home, or via a conversation about categories in the supermarket.

But is this theory of change correct? That is, does the provision of knowledge and activities lead to higher-quality play? 
Alternatively, by focusing parents on a specific activity, this approach could be flawed, causing parents to over-focus on achieving the superficial goals of the activity. 
This problem might be especially likely with video messages, which could encourage parents to try to mimic a model's specific speech and/or actions.
Attempting to reproduce such surface details of a video-guided activity could in turn result in less high-quality talk, with less responsiveness to their child's play.
Another possibility is that these messages might produce the desired effect, but only for those parents who already have a general orientation towards children's early learning.

Our current experiments were designed to make a direct test of this question: How do parents change their interactions with young children on the basis of short video parenting messages? 
In two experiments, we collected data from parent-child dyads in a local children's museum. 
We showed parents in the experimental group a single short video modeling an interactive toy-based activity along with a scientific justification. 
Parents in the control group received either no video (Experiment 1) or a video of a recent finding in developmental psychology (Experiment 2). 
We then gave the toys from the video to all dyads and videotaped their interactions, coding for caregivers' language quantity and quality as well as joint attention. 


# Experiment 1

In Experiment 1, we invited parents of 6- to 24-month-old infants visiting the Children's Discovery Museum in San Jose to complete video-guided activities from a commerical parenting app that delivers digital parenting advice in the form of short videos.
Parents were randomly assigned to one of two conditions: parents in the _Activity Video_ condition watched a video from the app (matched to their child's age), and then performed the activity with their child using the props from the video. 
Parents in the _No Video_ condition did not watch an activity video, but were given a set of the same age-appropriate props and asked to play with their infants as they normally would at home. 

### Discussion

In summary, while parents produced more word types and tokens after viewing the activity video, lexical diversity (both TTR and MTLD) was higher when parents were just asked to play as they normally would.
It may be that parents in the Activity Video condition, in their attempt to stick to the prescribed task, end up repeating themselves more, and indeed some differences in speech acts were notable: 
after the Activity Video, parents used more words related to requests (e.g., "Can I have X? / Give me X. Thank you!"), whereas after no intervention parents' language related more to invitations (e.g., "Are you ready?" / "Let's see.").
However, parents who watched an activity video also made more bids for JA with their child.
This did not result in a greater number of successful episodes of JA---passive or coordinated---than dyads in the No Video condition, although low reliability in passive JA coding (which led us to refine our JA coding guidelines for Experiment 2) may limit our ability to detect an effect there.
In sum, the results of Experiment 1 suggest that digital parenting advice can increase parents' efforts to engage their child in joint attention, expand the volume if not diversity of their speech, and can shift the type of speech acts towards more requests.


# Experiment 2

Experiment 1 found that parents who watched an activity video made more bids for joint attention and spoke more words tokens per minute to their children, but had lower lexical diversity compared to parents who played with their children as they normally would at home. 
Might it be that parents who are focused on a specific activity show reduced lexical diversity due to their focus on engaging their child in the activity?
Experiment 2 focuses on replicating the key findings using a stronger control group, as well as a restricted number of preregistered predictions.[^5]

Although the preregistration implied the use of standard linear mixed-effects regression through the specification of adopting an alpha level of .005 for statistical significance, the non-convergence of some regressions led us to switch to Bayesian regression. Using a Bayesian analysis has the added benefit of not requiring arbitrary changes to alpha levels to correct for multiple comparisons (Gelman, 2008).


# General Discussion

We were interested in how digital parenting advice alters parents' interactions with their children. 
We specifically set out to test whether activity suggestions led to higher-quality play, a presupposition of many early parenting interventions. 
Our experiments explored this question by randomly assigning parents to different advice conditions and then observing their behavior in short free-play sessions, with quality of play assessed through measures of parent language and joint attention. 
In two experiments, we found that activity videos increased the rate of parents' bids for joint attention as compared with no video (Experiment 1) and a comparable science video (Experiment 2). 
In some cases---especially in older children---these bids were successful in increasing engagement. 
We also observed differences in parents' talk that were broadly similar across both experiments, with a greater quantity of language but a similar breadth of vocabulary (leading to lower measures of lexical diversity). 
Exploratory corpus analysis identified the words most characteristic of the activity videos as being related to requests (e.g., "give", "put", "take") whereas control conditions featured more invitational words (e.g., "say", "let", "like"), often asking about animal noises ("What does the X say?").

The short, activity-oriented parenting messages we used encouraged parents to make more attempts---both verbal and non-verbal---to engage their child, supporting their use as a component of interventions. 
Why were they successful? 
When parents are asked to play with their children in the presence of new toys, they may choose to follow their child's lead and engage in free play.
While free play is positive, it nevertheless results in less scaffolded activity than when parents are given a goal that suggests a repertoire of ways to guide their child. 
Parents may also persist in providing opportunities for their child to complete the activity, leading to more repetitive language but also more offers of engagement.

Our study has a number of limitations related to design and sample, each of which suggests possible future directions. 
First, our design was intentionally short and minimal; future studies should investigate whether changes in parents' speech and attempts to engage their children could persist across a longer timespan (perhaps with a broader set of activities being provisioned). 
A longer-term study would also address whether consistent increases in parent bids would lead children to respond by engaging more with their parent.
Second, our design assumes that parents have access to the materials needed to complete the suggested activities; this assumption may be unrealistic for any parent, but especially for the parents who are most likely to be targeted for early parenting interventions. 
Providing materials may be critical for the success of activity suggestions. 
Finally, our sample is a convenience sample drawn from a museum, but it skews towards higher socio-economic status households as well as those families who are well-disposed towards visiting a museum (perhaps because they value education) and are interested in participating in research. 
A key goal for future research is to assess the generality of these findings across populations. 


In sum, the results of this study show that digital parenting videos recommending play activities can lead to short-term increases in parents' attempts to engage their young children, both verbally and non-verbally. 

[^2]: Based on piloting, we estimated these activities would would only require three minutes to complete.

[^4]: 89% CIs are recommended for Bayesian analyses because unless the effective sample size (ESS) is on the order of 10,000, the 95% credible interval is unstable [@Kruschke2014; @McElreath2018; @bayestestR]. Our ESS ranges from 2,000-5,000, and thus we report the tighter, more stable interval.

# Acknowledgements

This work was supported by a gift and a contract from Kinedu, Inc. to the Language and Cognition Lab. 
Thanks to Samaher Radwan and Megan Merrick for behavioral coding of the videos, and to members of the Language and Cognition Lab at Stanford for helpful discussion.